# Generated by Django 4.2.2 on 2024-11-21 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='static/aliens/spngebob.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mail',
            name='recipients',
            field=models.ManyToManyField(related_name='recipient_gamertag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Help_Wanted_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamertag', models.CharField(max_length=64)),
                ('game', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_help_wanted_table', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
