# Generated by Django 4.2.2 on 2024-11-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliens', '0002_user_profile_pic_alter_mail_recipients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Help_Wanted_Table',
            new_name='HelpWantedTable',
        ),
    ]
