# Generated by Django 4.2.2 on 2024-12-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliens', '0004_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpwantedtable',
            name='game_day',
            field=models.CharField(default='Monday', max_length=64),
        ),
    ]
