# Generated by Django 4.2.2 on 2024-12-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliens', '0005_helpwantedtable_game_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/aliens/spongebob.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
