# Generated by Django 4.2.2 on 2024-11-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliens', '0003_rename_help_wanted_table_helpwantedtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='static/aliens/spongebob.jpg', upload_to=''),
        ),
    ]
